import 'package:flutter/material.dart';

class toyota_camry_view extends StatelessWidget {
  const toyota_camry_view({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          leading: IconButton(
              onPressed: () {
                Navigator.pop(context);
              },
              icon: Icon(Icons.arrow_back, color: Colors.red[600])),
          backgroundColor: Colors.blue[300],
          centerTitle: true,
          title: Text(
            'CAMRY',
            style: TextStyle(
                color: Colors.red[700],
                fontSize: 30,
                fontWeight: FontWeight.bold),
          ),
        ),
        body: Column(
          children: [
            Container(
              height: 250,
              child: ListView(
                scrollDirection: Axis.horizontal,
                children: [
                  SizedBox(
                    width: 20,
                  ),
                  Image.network(
                    'https://www.toyota.com.sg/showroom/new-models/-/media/2c81262903714eef866cc79be59f19ea.png',
                    width: 370,
                  ),
                  SizedBox(
                    width: 20,
                  ),
                  Image.network(
                    'https://s3.amazonaws.com/toyota.site.toyota-v5/tci-prod/toyota/media/build/cam/col/big/b22_k61ak_fl1_02ps_a.png?ck=02162022031051',
                    width: 370,
                  ),
                  SizedBox(
                    width: 20,
                  ),
                  Image.network(
                    'https://65e81151f52e248c552b-fe74cd567ea2f1228f846834bd67571e.ssl.cf1.rackcdn.com/ldm-images/2019-Toyota-Camry-CA-Platinum-White-Pearl-w-Black-Roof.png',
                    width: 370,
                  ),
                  SizedBox(
                    width: 20,
                  ),
                  Image.network(
                    'https://www.wardsauto.com/sites/wardsauto.com/files/styles/article_featured_retina/public/uploads/2018/04/cockpit1214.jpg?itok=hEG-1vUM',
                    width: 370,
                  ),
                ],
              ),
            ),
            Container(
              decoration: BoxDecoration(
                color: Colors.blue[200],
                borderRadius: BorderRadius.circular(38),
              ),
              height: 444,
              width: double.infinity,
              child: SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Column(
                  children: [
                    Row(
                      children: [
                        SizedBox(
                          height: 70,
                          width: 30,
                        ),
                        Text(
                          'TOYOTA CAMRY',
                          style: TextStyle(
                              color: Colors.red[700],
                              fontSize: 25,
                              fontWeight: FontWeight.bold),
                        ),
                      ],
                    ),
                    Row(
                      children: [
                        SizedBox(
                          height: 20,
                          width: 27,
                        ),
                        Text(
                          ' \$25,900',
                          style: TextStyle(
                              fontSize: 20, fontWeight: FontWeight.bold),
                        )
                      ],
                    ),
                    SizedBox(
                      height: 15,
                      width: 27,
                    ),
                    ConstrainedBox(
                      constraints: BoxConstraints(
                        maxWidth: 300,
                      ),
                      child: Text(
                        'The 2022 Toyota Camry shares a nameplate with the generations that came before, but its extroverted styling and performance model make it almost unrecognizable. That\'s because the current Camry is arguably the most compelling it has ever been. The standard, albeit humdrum, four-cylinder engine is economical and fine for daily driver duty. The hybrid version maximizes fuel economy, even if its acceleration is uneventful. That leaves the lusty 301-hp V-6 to pick up the pace, especially on the sport-tuned Camry TRD, which is actually entertaining to drive. While rivals like the Honda Accord and Hyundai Sonata are more refined and satisfying overall, the Toyota has its own desirable qualities, such as a full suite of standard active safety features and goodwill generated by decades of proven reliability.',
                        style: TextStyle(fontWeight: FontWeight.bold),
                      ),
                    )
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
